# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contentImg',
            field=models.ImageField(upload_to=gallery.models.UploadToPathAndRename('/home/ayman/Desktop/OSS/gallery/media/upload')),
        ),
    ]
