# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170514_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='contentImg',
            field=models.ImageField(upload_to=gallery.models.UploadToPathAndRename('/home/ahmmkh/Desktop/OSS_Project/OSS/gallery/media/upload')),
        ),
    ]
