# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('logged_in', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to=members.models.UploadToPathAndRename('/home/ayman/Desktop/OSS/gallery/media/upload'))),
            ],
        ),
    ]
