# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(default='', max_length=400)),
                ('img', models.CharField(default='', max_length=200)),
                ('contentVid', models.CharField(default='', max_length=400)),
                ('contentImg', models.ImageField(upload_to=gallery.models.UploadToPathAndRename('/home/ayman/Desktop/OSS/courses/media/upload'))),
                ('contentText', models.TextField()),
            ],
        ),
    ]
